### ISSUE TITLE
fails with 'abcbabcadadz'

### ISSUE THREAD

**Issue by mixtur** [jayrbolton/node-suffix-tree#5]
```js
const STree = require('@jayrbolton/suffix-tree');

STree.create('abcbabcadadz');
```

This throws an error

```
TypeError: Cannot read property 'start' of undefined
    at Object.addSingle (/home/runner/node_modules/@jayrbolton/suffix-tree/index.js:99:40)
    at Object.add (/home/runner/node_modules/@jayrbolton/suffix-tree/index.js:39:11)
    at Object.create (/home/runner/node_modules/@jayrbolton/suffix-tree/index.js:26:11)
    at /home/runner/index.js:3:7
    at Script.runInContext (vm.js:133:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by mixtur** [comment]
Probaby dupliate for https://github.com/jayrbolton/node-suffix-tree/issues/3
